//
//  ViewController.swift
//  QuickWisdom
//
//  Created by Şevval Ensarioğlu on 24.05.2024.
//

import UIKit

class ViewController: UIViewController {
    
    // Fortune cookie "Great success is coming your way.",
    let fortuneMessages: [String] = ["Adventure awaits you.",
        "You will find happiness in unexpected places.",
        "An exciting opportunity lies ahead.",
        "Believe in your dreams.",
        "Your kindness will lead you to greatness.",
        "A pleasant surprise is in your near future.",
        "You will soon embark on a wonderful journey.",
        "Good fortune will be yours.",
        "You will achieve your goals.",
        "A new friendship will bring joy into your life.",
        "Your hard work will soon pay off.",
        "Positive changes are on the horizon.",
        "You will discover new talents.",
        "A big project is in your future.",
        "You will overcome any challenges.",
        "Success will come to you naturally.",
        "You will find what you are looking for.",
        "Great things are in store for you.",
        "Your creativity will lead you to success.",
        "Happiness is just around the corner.",
        "A new adventure awaits you.",
        "Your positive attitude will bring good things.",
        "You will make a valuable discovery.",
        "Something wonderful is about to happen.",
        "You will find the answer you seek.",
        "Your efforts will be rewarded.",
        "A meaningful relationship is in your future.",
        "You will soon achieve a long-term goal.",
        "An unexpected opportunity will come your way.",
        "You will be recognized for your hard work.",
        "Your future is looking bright.",
        "You will make a positive impact on others.",
        "New experiences will enrich your life.",
        "You will reach new heights.",
        "A significant change is coming your way.",
        "Your dreams are within reach.",
        "You will find peace and contentment.",
        "A joyous event will take place soon.",
        "Your intuition will guide you to success.",
        "You will discover hidden strengths.",
        "Good news is on the way.",
        "Your determination will lead to victory.",
        "You will make a new and valuable connection.",
        "Your future is filled with promise.",
        "A new opportunity will present itself.",
        "You will find the courage to take a bold step.",
        "Success is within your grasp.",
        "You will experience something new and exciting.",
        "Your life is about to change for the better.",
        
        // Yes-weighted phrases
        "Absolutely, go for it.",
        "Yes, this is a great idea.",
        "You should definitely do it.",
        "Yes, now is the perfect time.",
        "Go ahead, you have the green light.",
        "Yes, this is the right choice.",
        "Yes, you will succeed.",
        "Definitely, you should proceed.",
        "Yes, everything is in your favor.",
        "Yes, it's a positive move.",
        "Yes, this will bring good results.",
        "You have the right idea, go for it.",
        "Yes, this is the way forward.",
        "Yes, your instincts are correct.",
        "Yes, it’s a great opportunity.",
        "Yes, you should take the chance.",
        "Yes, this is beneficial for you.",
        "Yes, success is guaranteed.",
        "Yes, you will achieve your goals.",
        "Yes, it's the perfect time.",
        "Yes, your plan is solid.",
        "Yes, this will work out well.",
        "Yes, it’s worth the effort.",
        "Yes, you are on the right path.",
        "Yes, it's a wise decision.",
        "Yes, you have the skills.",
        "Yes, it's a promising idea.",
        "Yes, you should take action.",
        "Yes, this will lead to success.",
        "Yes, it’s the right moment.",
        "Yes, trust your judgment.",
        "Yes, you will be rewarded.",
        "Yes, this is favorable for you.",
        "Yes, go for it with confidence.",
        "Yes, it’s a good move.",
        "Yes, your future looks bright.",
        "Yes, you will find success.",
        "Yes, it’s the best course of action.",
        "Yes, you will benefit from this.",
        "Yes, everything will turn out well.",
        "Yes, this is a great step.",
        "Yes, you are making the right choice.",
        "Yes, you will achieve great things.",
        "Yes, this is a positive direction.",
        "Yes, you will find fulfillment.",
        "Yes, it’s a beneficial decision.",
        "Yes, your efforts will pay off.",
        "Yes, it’s a worthwhile endeavor.",
        "Yes, you should go ahead with it.",
        "Yes, this is a smart move.",
        "Yes.", "Yes.", "Yes.", "Yes.", "Yes.", "Yes.", "Yes.", "Yes.",

        // No-weighted phrases
        "No, this is not the right time.",
        "No, it's better to wait.",
        "No, this might not work out.",
        "No, you should reconsider.",
        "No, the timing isn't right.",
        "No, this isn't a good idea.",
        "No, it's not advisable.",
        "No, you should hold off.",
        "No, there are better options.",
        "No, it’s not worth the risk.",
        "No, you should think twice.",
        "No, this will not yield good results.",
        "No, it’s not the best choice.",
        "No, it's not in your favor.",
        "No, this won't end well.",
        "No, it's better to be cautious.",
        "No, you should avoid this.",
        "No, it’s not beneficial for you.",
        "No, success is not guaranteed.",
        "No, it's not the right moment.",
        "No, your plan has flaws.",
        "No, this is not the best course of action.",
        "No, it’s not the right move.",
        "No, it’s not a wise decision.",
        "No, you should not proceed.",
        "No, there are too many risks.",
        "No, this isn't the best idea.",
        "No, you need more preparation.",
        "No, it’s better to explore other options.",
        "No, this won’t work out well.",
        "No, it’s not the right path.",
        "No, this could lead to failure.",
        "No, it’s not a good time.",
        "No, you need to rethink this.",
        "No, it’s not the right choice.",
        "No, this won't bring good results.",
        "No, it’s not favorable.",
        "No, you should avoid this action.",
        "No, there are better alternatives.",
        "No, this is not beneficial.",
        "No, it’s not the right step.",
        "No, this isn’t advisable.",
        "No, you should take a different approach.",
        "No, it’s not worth pursuing.",
        "No, you will not benefit from this.",
        "No, this is not a positive direction.",
        "No, it’s better to hold off.",
        "No, this is not a smart move.",
        "No, it’s not in your best interest.",
        "No, you should not take this action.",
        "No.",  "No.", "No.",  "No.", "No.",  "No.", "No.",  "No.",

        // Maybe-weighted phrases
        "Maybe, but consider all options.",
        "It's possible, but not certain.",
        "Perhaps, but think it through.",
        "Maybe, weigh the pros and cons.",
        "It's uncertain, proceed with caution.",
        "Possibly, but there are risks.",
        "Maybe, but seek advice first.",
        "It could work, but be prepared.",
        "Possibly, but consider alternatives.",
        "Maybe, but don't rush.",
        "It's a chance, but not a sure thing.",
        "Perhaps, but assess the situation.",
        "Maybe, but stay flexible.",
        "It's an option, but not the only one.",
        "Possibly, but be aware of challenges.",
        "Maybe, but evaluate carefully.",
        "It might work, but consider all factors.",
        "Possibly, but think about the consequences.",
        "Maybe, but gather more information.",
        "It could be, but be cautious.",
        "Perhaps, but weigh the potential outcomes.",
        "Maybe, but don't commit fully yet.",
        "It's possible, but not guaranteed.",
        "Possibly, but have a backup plan.",
        "Maybe, but think strategically.",
        "It might be, but stay alert.",
        "Possibly, but consider the timing.",
        "Maybe, but seek more insights.",
        "It's an option, but think long-term.",
        "Perhaps, but remain open-minded.",
        "Maybe, but don't overlook details.",
        "It could be, but analyze the risks.",
        "Possibly, but think holistically.",
        "Maybe, but consider the impact.",
        "It's a possibility, but proceed mindfully.",
        "Perhaps, but be prepared for changes.",
        "Maybe, but don't put all your eggs in one basket.",
        "It's possible, but stay grounded.",
        "Possibly, but think about the bigger picture.",
        "Maybe, but be realistic.",
        "It could work, but be vigilant.",
        "Perhaps, but don't ignore warning signs.",
        "Maybe, but stay adaptable.",
        "It's a chance, but not a certainty.",
        "Possibly, but be mindful of the risks.",
        "Maybe, but take it step by step.",
        "It might work out, but stay cautious.",
        "Possibly, but think about long-term effects.",
        "Maybe, but remain cautious.",
        "It's a possibility, but be prudent.",
        "Maybe.", "Maybe.", "Maybe.", "Maybe.","Maybe.", "Maybe.",
            
                                     
        //other fortune sentences
        "Your future is bright and full of possibilities.",
        "Happiness is coming your way soon.",
        "You will achieve your goals with hard work.",
        "A surprise gift is on its way to you.",
        "New opportunities will present themselves today.",
        "Trust your instincts; they will guide you well.",
        "A pleasant journey is in your near future.",
        "Someone close to you has good news.",
        "You are stronger than you think.",
        "Success is a journey, not a destination.",
        "Yes.",
        "No.",
        "It will happen.",
        "It will not happen.",
        "Absolutely.",
        "Definitely not.",
        "Maybe.",
        "Ask again later.",
        "Without a doubt.",
        "Very unlikely.",
        "You will find what you seek.",
        "Challenges are stepping stones to success.",
        "Good things take time.",
        "Patience is a virtue.",
        "Unexpected joys are coming your way.",
        "Believe in yourself.",
        "Yes, but not as you expect.",
        "No, but something better is coming.",
        "The answer is within you.",
        "Look for the signs.",
        "Positive changes are ahead.",
        "Be open to new ideas.",
        "Fortune favors the brave.",
        "Keep your goals in sight.",
        "A new friendship will blossom.",
        "Change is inevitable; embrace it.",
        "You will discover a hidden talent.",
        "Your hard work will pay off soon.",
        "Expect the unexpected.",
        "Now is the time to take a chance.",
        "Good fortune is on your side.",
        "You will receive good news.",
        "Something wonderful is about to happen.",
        "An exciting opportunity lies ahead.",
        "Your kindness will be rewarded.",
        "A positive attitude will bring you success.",
        "Trust the process.",
        "Yes, but be patient.",
        "No, but keep trying.",
        "Adventure awaits you this weekend.",
        "You will meet someone special today.",
        "Trust in your dreams and they will come true.",
        "A new perspective will come with the new day.",
        "You will be surrounded by love and happiness.",
        "Your hard work will soon pay off.",
        "Something lost will soon be found.",
        "You will have a pleasant surprise this week.",
        "Now is the time to try something new.",
        "Success is in your near future.",
        "An unexpected event will bring you joy.",
        "Your patience will be rewarded.",
        "An opportunity will present itself soon.",
        "You will conquer your fears.",
        "Happiness begins with a smile.",
        "A new friendship is on the horizon.",
        "Good news will come to you by mail.",
        "A fresh start will put you on your way.",
        "Someone will appreciate your kindness.",
        "Your creativity will be recognized.",
        "You will overcome any obstacles in your way.",
        "A pleasant surprise is waiting for you.",
        "Your talents will be rewarded.",
        "You will soon embark on a new journey.",
        "Believe in the power of positive thinking.",
        "You will make a difference in someone’s life.",
        "Good luck will follow you everywhere.",
        "A dream you have will come true.",
        "You will achieve great things.",
        "Success is a journey, enjoy the ride.",
        "You are destined for greatness.",
        "New experiences are on the horizon.",
        "You will soon receive a compliment.",
        "Your life will be filled with sunshine.",
        "A new challenge will bring new rewards.",
        "Your positive attitude will lead to success.",
        "You will find joy in unexpected places.",
        "A new hobby will bring you happiness.",
        "Your kindness will be repaid tenfold.",
        "The answer you seek is yes.",
        "The answer you seek is no.",
        "Good fortune will smile upon you.",
        "A close friend will bring you a gift.",
        "You will soon witness a miracle.",
        "Your future is full of hope and promise.",
        "You will achieve your heart's desire.",
        "Good things come to those who wait.",
        "You will enjoy good health and happiness.",
        "Success is just around the corner.",
        "You will find the key to your success.",
        "A brilliant concept will emerge from your thoughts.",
        "Unexpected support will come your way.",
        "Challenges will refine and improve your idea.",
        "Future success is built on today's creativity.",
        "Rewards will follow your innovative thinking.",
        "Widespread acclaim is on the horizon.",
        "Like-minded people will be drawn to you.",
        "A new opportunity will arise from your concept.",
        "Resources will become available at the right time.",
        "Lives will be positively impacted by your work.",
        "An evolution of your concept will surprise you.",
        "Inspiration will spread from your initial thought.",
        "A mentor will appear when needed most.",
        "Peace of mind accompanies your creative process.",
        "New aspects of your project will reveal themselves.",
        "Positive attention will follow your efforts.",
        "New doors will open as you develop your idea.",
        "A breakthrough moment is near.",
        "Joy will be a byproduct of your project.",
        "Success will be built step by step.",
        "Recognition will come from unexpected places.",
        "A significant achievement is within reach.",
        "The right people will gravitate towards you.",
        "Perfect timing will enhance your concept.",
        "Obstacles will turn into opportunities.",
        "A lasting impact will result from your work.",
        "Financial support will find its way to you.",
        "Expect your project to exceed expectations.",
        "A long-standing problem will be solved.",
        "Clarity will come to a complex situation.",
        "Others will be inspired by your initiative.",
        "Personal growth will accompany your journey.",
        "Community embrace is forthcoming.",
        "Future projects will build on this foundation.",
        "Goals will become clearer and closer.",
        "Enthusiasm will meet your efforts.",
        "Longevity will mark your success.",
        "Innovation will be your hallmark.",
        "New discoveries will spring from your work.",
        "This is the start of something monumental.",
                                     
        // no but positive
        "Now may not be the best time, but opportunities are coming.",
        "Reconsider your options, better things are ahead.",
        "It's best to wait for the right moment.",
        "This path may not be right, but a better one will appear.",
        "It's not advisable now, but soon it will be.",
        "Think it through carefully, great rewards await your patience.",
        "The timing isn't right now, but it will be soon.",
        "Explore other options, success is just around the corner.",
        "It's not worth the risk today, but tomorrow holds promise.",
        "Be cautious now, brighter days are coming.",
        "This could lead to problems now, but will be solved soon.",
        "Take a step back today, leap forward tomorrow.",
        "This isn't the best choice now, but a better one will come.",
        "It's not in your best interest now, but it will be soon.",
        "Avoid this direction today, a better path will emerge.",
        "It's not a good idea right now, but it will be soon.",
        "You need more information now, clarity is on the way.",
        "It's better to be safe today, tomorrow will be brighter.",
        "Consider alternative solutions now, the best one is coming.",
        "It's not the right time to act today, but it will be soon.",
        "There are too many uncertainties today, but they will clear up.",
        "This will not yield good results today, but will in the future.",
        "Take some time to rethink, a better plan is forming.",
        "It's not the right move now, but it will be soon.",
        "This decision could backfire now, but success is near.",
        "Wait for a better opportunity, it's just around the corner.",
        "It's not beneficial for you today, but it will be soon.",
        "You should not proceed today, but the right time is near.",
        "This isn't the best course of action now, but it will be soon.",
        "Success is not guaranteed today, but it will be tomorrow.",
        "It's better to hold off now, brighter opportunities are coming.",
        "There are better options available soon.",
        "It's not worth pursuing today, but it will be tomorrow.",
        "You need to reconsider now, the right path is near.",
        "This isn't a wise decision today, but it will be soon.",
        "It's not the best choice now, but it will be tomorrow.",
        "Take more time to decide, the best choice is forming.",
        "There are too many risks today, but they will lessen soon.",
        "This isn't favorable now, but it will be soon.",
        "Avoid this plan today, but a better one is coming.",
        "Think of other possibilities now, the right one is near.",
        "It’s not the right step today, but it will be soon.",
        "Explore other opportunities now, the best is yet to come.",
        "It’s not advisable at the moment, but it will be soon.",
        "This could lead to failure today, but success is near.",
        "It’s not in your favor now, but it will be soon.",
        "It’s better to wait for now, good things are coming.",
        "There are too many drawbacks today, but they will clear up.",
        "You need to think more carefully now, clarity is on the way.",
        "This isn't the right approach now, but it will be soon.",
    
        //her sey cok guzel olacak
        "Everything will turn out wonderfully.",
        "Bright days are ahead.",
        "Your future is filled with endless possibilities.",
        "Happiness and success are on their way.",
        "Good things are coming your way.",
        "You are destined for great joy.",
        "Wonderful surprises are in store for you.",
        "Your hard work will lead to amazing rewards.",
        "Your life is about to become even more beautiful.",
        "Expect fantastic outcomes in the near future.",
        "You are on the path to great happiness.",
        "Joy and success are just around the corner.",
        "Your dreams are about to come true.",
        "Great things are on the horizon.",
        "Everything you wish for will come to fruition.",
        "You will experience profound happiness.",
        "Your efforts will lead to great achievements.",
        "A bright future awaits you.",
        "Amazing opportunities are coming your way.",
        "Your life will be filled with love and joy.",
        "Expect wonderful things to happen.",
        "Your positive energy will attract great results.",
        "You are on the verge of a wonderful breakthrough.",
        "Happiness will fill your days.",
        "Success and joy are intertwined in your future.",
        "Every day will bring you closer to your dreams.",
        "Your future is brighter than you can imagine.",
        "You will find great fulfillment in your endeavors.",
        "Beautiful moments are waiting for you.",
        "You are surrounded by positive energy.",
        "Your journey is leading you to wonderful places.",
        "Incredible experiences await you.",
        "You are about to embark on a joyous adventure.",
        "Your life will be filled with amazing moments.",
        "Wonderful things are in store for you.",
        "Your future holds great promise and joy.",
        "You will achieve remarkable success.",
        "Joyful surprises will brighten your days.",
        "Your dreams will manifest in beautiful ways.",
        "Happiness is your constant companion.",
        "You are destined for a life of joy and abundance.",
        "Great achievements are within your reach.",
        "You will find immense joy in your journey.",
        "Your future is a canvas of beautiful possibilities.",
        "Expect happiness to be your guide.",
        "Your life is about to become incredibly wonderful.",
        "You will be blessed with endless joy.",
        "Wonderful experiences are coming your way.",
        "Your future is a tapestry of beautiful moments.",
        "Great things are unfolding for you now."
    
    ]

   
    @IBOutlet weak var messageLabel: UILabel!
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    
    }

    
    @IBAction func inspireMeButton(_ sender: Any) {
        showRandomMessage()

    }
    
    func showRandomMessage(){
        if let randomMessage = fortuneMessages.randomElement() {
            messageLabel.text = randomMessage
        }
    }
}


